# Generated by Django 4.2.14 on 2024-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="test_field",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
